#!/bin/bash

me=/mn/stornext/u3/krisjand/quiet_svn/oslo/src/f90/map_editor/map_editor
mask_dir=/mn/stornext/u3/krisjand/stornext/npipe_highres/data_npipe

freqs=("30" "44" "70" "100" "143" "217" "353" "545" "857")
#freqs=("545" "857")

masks=("commander_dx12_mask_n0256_likelihood_v2.fits"
    "commander_dx12_mask_n0512_likelihood_v2.fits"
    "commander_dx12_mask_n1024_likelihood_v2.fits"
    "commander_dx12_mask_n2048_likelihood_v2.fits")

masksfullsky=("mask_fullsky_n0256_tqu.fits"
    "mask_fullsky_n0512_tqu.fits"
    "mask_fullsky_n1024_tqu.fits"
    "mask_fullsky_n2048_tqu.fits")


if [ $# -ne 5 ] || [ "$1" = "help" ]; then
   echo ""
   echo "Syntax: calc_gain_mono_offset_between_skymaps [map label (pre band label)] [nside] [smoothing (arcmins)] [map label comparison] [comparison directory] "
   echo ""
   echo "e.g. calc_gain_mono_offset_between_skymaps npipe6v1 256 40 npipe5v21 ../npipe5v21"
   echo ""
   exit
fi

map_label=$1
ns_HFI=$2
nside=$(printf "%04d" $2)

if [ $ns_HFI -eq 2048 ];then
    nside_LFI=1024
else
    ns_LFI=$ns_HFI
    nside_LFI=$(printf "%04d" $ns_HFI)
fi
arcmin=$3
comp_label=$4
if [ "${5:$((${#5}-1)):1}" = "/" ]; then
    comp_dir="${5:0:$((${#5}-1))}"
else
    comp_dir="${5}"
fi

offset_file="mono_fits_${map_label}_vs_${comp_label}.dat"
gain_file="gain_fits_${map_label}_vs_${comp_label}.dat"

echo "# Gain difference ${map_label} vs ${comp_label}" > $gain_file
echo "# map_gain = gain*comp_gain" >> $gain_file
echo "#-----------------------------" >> $gain_file
echo "# Band     Gain" >> $gain_file

echo "# Offset difference ${map_label} vs ${comp_label}" > $offset_file
echo "# map_offset = offset + comp_offset" >> $offset_file
echo "#-----------------------------" >> $offset_file
echo "# Band     Offset" >> $offset_file


for ((i=0; i<${#freqs[@]}; i++)) ; do
    freq=${freqs[$i]} #Frequency
    
    if [ $freq -lt 100 ]; then
	ns=$ns_LFI
	

	in_str="${map_label}"*${freq}*"_n${nside_LFI}_${arcmin}arcmin"*".fits"
    else
	ns=$ns_HFI
	in_str="${map_label}"*${freq}*"_n${nside}_${arcmin}arcmin"*".fits"
    fi
    for inputmap in $in_str; do  # input maps (nside 256), with directory
	compmap=${inputmap/$map_label/$comp_label}
	compmap=$comp_dir/$compmap #Map to adjust to
	
	if [ $freq -lt 100 ]; then
	    if [[ $inputmap = *"LFI"* ]]; then
		in_a="${inputmap/${freq}_/ }"
	    else
		in_a="${inputmap/_0${freq}/ 0${freq}}"
	    fi
	    in_a="${in_a/_map/ }"
	    in_a="${in_a/_bmap/ }"
	    in_a=($in_a)
	    channel=${in_a[1]}
	    
	else
	    in_a="${inputmap/_${freq}/ ${freq}}"
	    in_a="${in_a/_map/ }"
	    in_a="${in_a/_bmap/ }"
	    in_a=($in_a)
	    channel=${in_a[1]}
	fi
	echo "----------------------------------------------------------------------------------"
	echo "Frequency: " ${freq}
	echo "Band: $channel"
	echo "Input map: " ${inputmap}
	echo "Comparing with: " ${compmap}
	echo "----------------------------------------------------------------------------------"

	if [ $ns -eq 256 ];then
	    j=0
	elif [ $ns -eq 512 ];then
	    j=1
	elif [ $ns -eq 1024 ];then
	    j=2
	elif [ $ns -eq 2048 ];then
	    j=3
	fi
	#-------------------- FIT GAIN OFFSET - GET GAIN AND OFFSET ----------------------
	echo "Fitting using mono- and dipole correction"
	$me fit_gain_offset_dipole ${compmap} ${inputmap} ${mask_dir}/${masksfullsky[$j]} ${mask_dir}/${masks[$j]} residual.fits 2>/dev/null > fit_gain_temp2.txt #save output and ignore error

	# EXTRACT OFFSET OUTPUT
	tr -s '[:space:]' < fit_gain_temp2.txt # Remove double spaces
	offset=($(tail -n 1 fit_gain_temp2.txt | grep -oP '(?<=offset\ =\ ).*'))
	# EXTRACT GAIN OUTPUT
	gain=$(tail -n 1 fit_gain_temp2.txt | grep -oP '(?<=gain\ =\ ).*(?=,)')
	gain=$(bc -l <<< "1/$gain") # 1/gain calculator

	echo "gain: $gain offset:  ${offset[0]} ${offset[1]} ${offset[2]} ${offset[3]}"

	offset=$(echo -"($offset)" | bc -l) # Invert offset

	rm fit_gain_temp2.txt 2>/dev/null
	rm residual.fits 2>/dev/null

	echo "-----------------------------------------------------------"
	echo "Fitting using only monopole correction"
	$me fit_gain_offset ${compmap} ${inputmap} ${mask_dir}/${masksfullsky[$j]} ${mask_dir}/${masks[$j]} residual.fits 2>/dev/null > fit_gain_temp.txt #save output and ignore error

	# EXTRACT OFFSET OUTPUT
	line=$(tail -n 1 fit_gain_temp.txt)
	line=($line)
	gain=${line[0]}
	offset=${line[1]}
	echo "gain_inmap = gain*gain_refmap"
	echo "gain: $gain"
	printf "%6s   %12s \n" $channel $gain >> $gain_file
	echo "temp_amp inmap = offset + temp_amp refmap"
	echo "offset:  ${offset[0]}"
	printf "%6s   %12s \n" $channel $offset >> $offset_file

	

	rm fit_gain_temp.txt 2>/dev/null
	rm residual.fits 2>/dev/null




#Usage: map_editor fit_gain_offset_dipole [xmap] [ymap] [gain mask] [offset/dipole mask] [output residualfile]

#Usage: map_editor fit_gain_offset [xmap] [ymap] [gain mask] [offset mask] [output residualfile]'

    done
done
echo "-------------------------------------"
echo "FINISHED"
echo ""
