#!/bin/bash

init_dir="/mn/stornext/u3/krisjand/stornext/npipe_highres/data_npipe/"

maps=("res_030_c0001_k"$1".fits"
"res_044_c0001_k"$1".fits"
"res_070_c0001_k"$1".fits"
"res_100_c0001_k"$1".fits"
"res_143_c0001_k"$1".fits"
"res_217_c0001_k"$1".fits"
"res_353_c0001_k"$1".fits"
"res_545_c0001_k"$1".fits"
"res_857_c0001_k"$1".fits"
"chisq_c0001_k"$1".fits"
"cmb_c0001_k"$1".fits"
"co_c0001_k"$1".fits"
"dust_T_c0001_k"$1".fits"
"dust_beta_c0001_k"$1".fits"
"dust_c0001_k"$1".fits"
"synch_beta_c0001_k"$1".fits"
"synch_c0001_k"$1".fits")

nside=512
for i in ${!maps[@]}; do
    map_editor smooth g2g ${maps[$i]} 0 1500 $nside 0. 30. ${maps[$i]/.fits/_n0512_highres_smooth_30min.fits}

done


echo "Plotting amplitudes"
map2png dust_c0001_k$1_n0512_highres_smooth_30min.fits -bar -max 1000
map2png synch_c0001_k$1_n0512_highres_smooth_30min.fits -bar -max 1000 -min 0
map2png co_c0001_k$1_n0512_highres_smooth_30min.fits -bar -max 2 -min 0
#map2png co10_c0001_k$1.fits -bar -max 2 -min 0
#map2png co21_c0001_k$1.fits -bar -max 2 -min 0
#map2png co32_c0001_k$1.fits -bar -max 2 -min 0
#map2png hcn_c0001_k$1.fits -bar -max 1 -min 0
map2png cmb_c0001_k$1_n0512_highres_smooth_30min.fits -bar -range 250
#map2png cmb_Cl_c0001_k$1.fits -bar -range 250
#map2png sz_c0001_k$1.fits sz_c0001_k${1}.png -bar -min 0 -max 1e-6
#patch2img -lon 270 -lat 80 -size 40 -res 4 sz_c0001_k$1.fits -grid 10 -min 0 -max 5e-6

echo "Plotting indices"
map2png dust_beta_c0001_k$1_n0512_highres_smooth_30min.fits  -bar -min 1.3 -max 2.0
map2png dust_T_c0001_k$1_n0512_highres_smooth_30min.fits  -bar -min 14 -max 30
#map2png dust_Td_c0001_k$1_nosmooth.fits  -bar -min 14 -max 30
map2png synch_beta_c0001_k$1_n0512_highres_smooth_30min.fits  -bar -min -4.0 -max -1.5

#map2png ${init_dir}init_dust_beta_npipe4v205_trygve_n2048_v13.2.fits init_dust_beta_npipe4v205_trygve_n2048_v13.2.png -bar -min 1.3 -max 2.0
#map2png ${init_dir}init_dust_T_npipe4v205_trygve_n2048_v13.2.fits init_dust_T_npipe4v205_trygve_n2048_v13.2.png -bar -min 14 -max 30
#map2png ${init_dir}init_synch_beta_npipe4v205_trygve_n2048_v13.2.fits init_synch_beta_npipe4v205_trygve_n2048_v13.2.png -bar -min -4.0 -max -1.5

#map2png ame1_nup_c0001_k$1.fits  -bar -min 17 -max 23
#map2png ame2_nup_c0001_k$1.fits  -bar -min 15 -max 40
#map2png ff_EM_c0001_k$1.fits  -bar -min 0 -max 100
#map2png ff_T_e_c0001_k$1.fits  -bar -min 5000 -max 8000

echo "Plotting chisq"
map2png chisq_c0001_k$1_n0512_highres_smooth_30min.fits -bar -max 40 -min 0

##echo "Plotting residuals"
#map2png -bar -range 10 residual_030_c01_k$1.fits
#map2png -bar -range 10 residual_044_c01_k$1.fits
#map2png -bar -range 10 residual_070_c01_k$1.fits
#map2png -bar -range 10 residual_100-1a_c01_k$1.fits
#map2png -bar -range 10 residual_100-1b_c01_k$1.fits
#map2png -bar -range 10 residual_100-2a_c01_k$1.fits
#map2png -bar -range 10 residual_100-2b_c01_k$1.fits
#map2png -bar -range 10 residual_100-3a_c01_k$1.fits
#map2png -bar -range 10 residual_100-3b_c01_k$1.fits
#map2png -bar -range 10 residual_100-4a_c01_k$1.fits
#map2png -bar -range 10 residual_100-4b_c01_k$1.fits
#map2png -bar -range 10 residual_143_c01_k$1.fits
#map2png -bar -range 10 residual_217-1_c01_k$1.fits
#map2png -bar -range 10 residual_217-2_c01_k$1.fits
#map2png -bar -range 10 residual_217-3_c01_k$1.fits
#map2png -bar -range 10 residual_217-4_c01_k$1.fits
#map2png -bar -range 10 residual_217-5a_c01_k$1.fits
#map2png -bar -range 10 residual_217-5b_c01_k$1.fits
#map2png -bar -range 10 residual_217-6a_c01_k$1.fits
#map2png -bar -range 10 residual_217-6b_c01_k$1.fits
#map2png -bar -range 10 residual_217-7a_c01_k$1.fits
#map2png -bar -range 10 residual_217-7b_c01_k$1.fits
#map2png -bar -range 10 residual_217-8a_c01_k$1.fits
#map2png -bar -range 10 residual_217-7b_c01_k$1.fits
#map2png -bar -range 10 residual_353-1_c01_k$1.fits
#map2png -bar -range 10 residual_353-2_c01_k$1.fits
#map2png -bar -range 10 residual_353-3a_c01_k$1.fits
#map2png -bar -range 10 residual_353-3b_c01_k$1.fits
#map2png -bar -range 10 residual_353-4a_c01_k$1.fits
#map2png -bar -range 10 residual_353-4b_c01_k$1.fits
#map2png -bar -range 10 residual_353-5a_c01_k$1.fits
#map2png -bar -range 10 residual_353-5b_c01_k$1.fits
#map2png -bar -range 10 residual_353-6a_c01_k$1.fits
#map2png -bar -range 10 residual_353-6b_c01_k$1.fits
#map2png -bar -range 10 residual_353-7_c01_k$1.fits
#map2png -bar -range 10 residual_353-8_c01_k$1.fits
#map2png -bar -range 1e-2 residual_545_c01_k$1.fits
#map2png -bar -range 1e-2 residual_857_c01_k$1.fits
#
##echo "Plotting residuals"
#map2png -bar -range 10 residual_030_c01_k$1.fits
#map2png -bar -range 10 residual_044_c01_k$1.fits
#map2png -bar -range 10 residual_070_c01_k$1.fits
#map2png -bar -range 10 residual_100_c01_k$1.fits
#map2png -bar -range 10 residual_143_c01_k$1.fits
#map2png -bar -range 10 residual_217_c01_k$1.fits
#map2png -bar -range 10 residual_353_c01_k$1.fits
#map2png -bar -range 1e-2 residual_545_c01_k$1.fits
#map2png -bar -range 1e-2 residual_857_c01_k$1.fits
##echo "Plotting residuals"
#map2png -bar -range 10 residual_030_c01_k$1.fits
#map2png -bar -range 10 residual_044_c01_k$1.fits
#map2png -bar -range 10 residual_070_c01_k$1.fits
#map2png -bar -range 10 residual_100_c01_k$1.fits
#map2png -bar -range 10 residual_143_c01_k$1.fits
#map2png -bar -range 10 residual_217_c01_k$1.fits
#map2png -bar -range 10 residual_353_c01_k$1.fits
#map2png -bar -range 1e-2 residual_545_c01_k$1.fits
#map2png -bar -range 1e-2 residual_857_c01_k$1.fits
#
##echo "Plotting residuals"
#map2png -bar -range 10 residual_030_c01_k$1.fits
#map2png -bar -range 10 residual_044_c01_k$1.fits
#map2png -bar -range 10 residual_070_c01_k$1.fits
#map2png -bar -range 10 residual_100_c01_k$1.fits
#map2png -bar -range 10 residual_143_c01_k$1.fits
#map2png -bar -range 10 residual_217_c01_k$1.fits
#map2png -bar -range 10 residual_353_c01_k$1.fits
#map2png -bar -range 1e-2 residual_545_c01_k$1.fits
#map2png -bar -range 1e-2 residual_857_c01_k$1.fits
#
map2png -bar -range 10 res_030_c0001_k$1_n0512_highres_smooth_30min.fits
map2png -bar -range 10 res_044_c0001_k$1_n0512_highres_smooth_30min.fits
map2png -bar -range 10 res_070_c0001_k$1_n0512_highres_smooth_30min.fits
map2png -bar -range 10 res_100_c0001_k$1_n0512_highres_smooth_30min.fits
map2png -bar -range 10 res_143_c0001_k$1_n0512_highres_smooth_30min.fits
map2png -bar -range 10 res_217_c0001_k$1_n0512_highres_smooth_30min.fits
map2png -bar -range 10 res_353_c0001_k$1_n0512_highres_smooth_30min.fits
map2png -bar -range 1e-2 res_545_c0001_k$1_n0512_highres_smooth_30min.fits
map2png -bar -range 1e-2 res_857_c0001_k$1_n0512_highres_smooth_30min.fits
