#!/bin/bash

m2p=/mn/stornext/u3/hke/local/bin/map2png
mask_dir=/mn/stornext/u3/krisjand/stornext/npipe_lowres/data/mask_dir

if [ $# -lt 1 ]; then
  echo "plot_maps [sample number]"
  exit
else
  echo "Plotting sample(s):" $@
fi

#read -p "Degree: [40/60] " deg
read -p "nside: [64/256] " nside
read -p "version: [e.g. 'v1'] " version

#nside=64
#if [ "$nside" = "256" ]; then
#  if [ "$deg" = "60" ]; then
#    refmap_dx12=~/master/cdata/like/refmap/refmap_cmb_dx12_cl_v2_n0256_60arcmin_k00800_MDCOR.fits
#    refmap_dx11=~/master/cdata/like/refmap/refmap_cmb_dx11_cl_v3.3_n0256_60arcmin_k00290_MDCOR.fits
#  else
#    refmap_dx12=~/master/cdata/like/refmap/refmap_cmb_dx12_cl_v2_n0256_k00800_MDCOR.fits
#    refmap_dx11=~/master/cdata/like/refmap/refmap_cmb_dx11_cl_v3.3_n0256_k00290_MDCOR.fits
#  fi
#else
#  if [ "$deg" = "60" ]; then
#    refmap_dx12=~/master/cdata/like/refmap/refmap_cmb_dx12_cl_v2_n0064_60arcmin_k00800_MDCOR.fits
#    refmap_dx11=~/master/cdata/like/refmap/refmap_cmb_dx11_cl_v3.3_n0064_60arcmin_k00290_MDCOR.fits
#  else
#    refmap_dx12=~/master/cdata/like/refmap/refmap_cmb_dx12_cl_v2_n0064_k00800_MDCOR.fits
#    refmap_dx11=~/master/cdata/like/refmap/refmap_cmb_dx11_cl_v3.3_n0064_k00290_MDCOR.fits
#  fi
#fi

me=/mn/stornext/u3/krisjand/quiet_svn/oslo/src/f90/map_editor/map_editor
#Refmaps for dx12 and 11 (with dipole)
#refmap_dx12=~/master/cdata/like/refmap/refmap_cmb_dx12_cl_v2_n0256_k00800.fits 
#refmap_dx11=~/master/cdata/like/refmap/refmap_cmb_dx11_cl_v3.3_n0256_k00290.fits

for n in $@; do
  echo "_____ Plotting sample $n _____"
  num=$(printf "%05d\n" $n)
  echo "---- Plotting CMB ----"
  $m2p cmb_c0001_k$num.fits -bar -range 2500


  cmb_dp_path=/mn/stornext/u3/krisjand/stornext/npipe_lowres/cmb_dipole
  chains_path=$(pwd) #getting path
  ch_path2=(${chains_path/'npipe_lowres/'/'npipe_lowres '}) #splitting chains-directory from npipe_lowres path
  ch_str=${ch_path2[1]} #getting the name of the chains-directory

  if [ $nside -eq 64 ]; then
      masks=("mask_chisq_15band_n064_v2_ptsrc.fits"
	  "mask_proc_v1_n0064.fits" 
	  "mask_proc_v2_n0064.fits" 
	  "mask_proc_v3_n0064.fits")
  elif [ $nside -eq 256 ]; then
      masks=("mask_chisq_15band_n256_v2_ptsrc.fits"
	  "mask_proc_v1_n0256.fits" 
	  "mask_proc_v2_n0256.fits" 
	  "mask_proc_v3_n0256.fits")
  else 
      masks="none"
  fi    
  if [ "${masks[0]}" = "none" ]; then
      echo "No masks for MD subtraction in CMB"
  else
      mask_str=("mask_chisq_15band"
	  "mask_proc_v1" 
	  "mask_proc_v2" 
	  "mask_proc_v3")
      out_file=${ch_str/chains_ml_/}
      out_file=${out_file/_shb_dipole/}
      out_file=cmb_${out_file}_k${num}.txt

      echo "# CMB (mono &) dipole parameters" > $cmb_dp_path/$out_file
      echo "#Chain: $ch_str" >> $cmb_dp_path/$out_file
      
      for ((j=0;j<${#masks[@]};j++));do
	  mask_cmb=${masks[$j]}
	  echo "" >> $cmb_dp_path/$out_file
	  echo "" 
	  echo "#Mask: $mask_cmb" >> $cmb_dp_path/$out_file
	  echo "Mask: $mask_cmb"
	  
	  $me subtract_mono_dipole cmb_c0001_k$num.fits $mask_dir/$mask_cmb cmb_c0001_k${num}_${mask_str[$j]}.fits 2>&1 | tee cmb_slurm.txt

	  cmb_line=$(grep -F "Coefficients" cmb_slurm.txt)
	  rm cmb_slurm.txt
	  echo " MD coeffs: [monopole] [dipole_x] [dipole_y] [dipole_z]" >> $cmb_dp_path/$out_file
	  echo " MD coeffs: [monopole] [dipole_x] [dipole_y] [dipole_z]"
	  echo "#$cmb_line" >> $cmb_dp_path/$out_file
	  cmb_line="${cmb_line/'Coefficients ='/}"
	  cmb_coeffs=($cmb_line)
	  cmb_amp=$(bc <<< "sqrt(${cmb_coeffs[1]}^2 + ${cmb_coeffs[2]}^2 + ${cmb_coeffs[3]}^2)")
	  echo "#Dipole_ampl (uK): $cmb_amp" >> $cmb_dp_path/$out_file
	  echo "#Dipole_ampl (uK): $cmb_amp"

	  $m2p cmb_c0001_k${num}_${mask_str[$j]}.fits -bar -range 250
      done
  fi
  #$m2p cmb_Cl_c0001_k$num.fits -bar -range 250
  #$m2p sz_c0001_k$num.fits sz_c0001_k${1}.png -bar -min 0 -max 1e-6
  #patch2img -lon 270 -lat 80 -size 40 -res 4 sz_c0001_k$num.fits -grid 10 -min 0 -max 5e-6

#  echo "---- Plotting dx12 diff ----"
#  map_editor subtract $refmap_dx12 cmb_c0001_k$num.fits cmb_diff_dx12-npipe_k$num.fits
#  $m2p cmb_diff_dx12-npipe_k$num.fits -bar -range 10

#  echo "---- Plotting dx11 diff ----"
#  map_editor subtract $refmap_dx11 cmb_c0001_k$num.fits cmb_diff_dx11-npipe_k$num.fits
#  $m2p cmb_diff_dx11-npipe_k$num.fits -bar -range 10

  echo "---- Plotting amplitudes ----"
  $m2p dust_c0001_k$num.fits -bar -max 1000
  $m2p synch_c0001_k$num.fits -bar -max 1000 -min 0
  $m2p ame1_c0001_k$num.fits -bar -max 300
  $m2p ame2_c0001_k$num.fits -bar -max 300

  $m2p co_c0001_k$num.fits -bar -max 2 -min 0
  $m2p co-100_c0001_k$num.fits -bar -max 2 -min 0
  $m2p co-217_c0001_k$num.fits -bar -max 2 -min 0
  $m2p co-353_c0001_k$num.fits -bar -max 2 -min 0

  $me scale co-100_c0001_k$num.fits co-100_c0001_k${num}_highres_units.fits 11.06
  $me scale co-217_c0001_k$num.fits co-217_c0001_k${num}_highres_units.fits 14.01
  $me scale co-353_c0001_k$num.fits co-353_c0001_k${num}_highres_units.fits 12.24

  $m2p co-100_c0001_k${num}_highres_units.fits co10_c0001_highres_units_max2_k${num}.png -bar -max 2 -min 0
  $m2p co-100_c0001_k${num}_highres_units.fits co10_c0001_highres_units_max0.2_k${num}.png -bar -max 0.2 -min 0
  $m2p co-100_c0001_k${num}_highres_units.fits co10_c0001_highres_units_max10_k${num}.png -bar -max 10 -min 0
  $m2p co-100_c0001_k${num}_highres_units.fits co10_c0001_highres_units_max100_k${num}.png -bar -max 100 -min 0
  $m2p co-217_c0001_k${num}_highres_units.fits co21_c0001_highres_units_max2_k${num}.png -bar -max 2 -min 0
  $m2p co-217_c0001_k${num}_highres_units.fits co21_c0001_highres_units_max0.2_k${num}.png -bar -max 0.2 -min 0
  $m2p co-217_c0001_k${num}_highres_units.fits co21_c0001_highres_units_max10_k${num}.png -bar -max 10 -min 0
  $m2p co-217_c0001_k${num}_highres_units.fits co21_c0001_highres_units_max100_k${num}.png -bar -max 100 -min 0
  $m2p co-353_c0001_k${num}_highres_units.fits co32_c0001_highres_units_max2_k${num}.png -bar -max 2 -min 0
  $m2p co-353_c0001_k${num}_highres_units.fits co32_c0001_highres_units_max0.2_k${num}.png -bar -max 0.2 -min 0
  $m2p co-353_c0001_k${num}_highres_units.fits co32_c0001_highres_units_max10_k${num}.png -bar -max 10 -min 0
  $m2p co-353_c0001_k${num}_highres_units.fits co32_c0001_highres_units_max100_k${num}.png -bar -max 100 -min 0

  $m2p co-100_c0001_k${num}.fits co10_c0001_lowres_units_max2_k${num}.png -bar -max 2 -min 0
  $m2p co-100_c0001_k${num}.fits co10_c0001_lowres_units_max0.2_k${num}.png -bar -max 0.2 -min 0
  $m2p co-100_c0001_k${num}.fits co10_c0001_lowres_units_max10_k${num}.png -bar -max 10 -min 0
  $m2p co-100_c0001_k${num}.fits co10_c0001_lowres_units_max100_k${num}.png -bar -max 100 -min 0
  $m2p co-217_c0001_k${num}.fits co21_c0001_lowres_units_max2_k${num}.png -bar -max 2 -min 0
  $m2p co-217_c0001_k${num}.fits co21_c0001_lowres_units_max0.2_k${num}.png -bar -max 0.2 -min 0
  $m2p co-217_c0001_k${num}.fits co21_c0001_lowres_units_max10_k${num}.png -bar -max 10 -min 0
  $m2p co-217_c0001_k${num}.fits co21_c0001_lowres_units_max100_k${num}.png -bar -max 100 -min 0
  $m2p co-353_c0001_k${num}.fits co32_c0001_lowres_units_max2_k${num}.png -bar -max 2 -min 0
  $m2p co-353_c0001_k${num}.fits co32_c0001_lowres_units_max0.2_k${num}.png -bar -max 0.2 -min 0
  $m2p co-353_c0001_k${num}.fits co32_c0001_lowres_units_max10_k${num}.png -bar -max 10 -min 0
  $m2p co-353_c0001_k${num}.fits co32_c0001_lowres_units_max100_k${num}.png -bar -max 100 -min 0
  #$m2p co10_c0001_k$num.fits -bar -max 2 -min 0
  #$m2p co21_c0001_k$num.fits -bar -max 2 -min 0
  #$m2p co32_c0001_k$num.fits -bar -max 2 -min 0
  $m2p hcn_c0001_k$num.fits -bar -max 1 -min 0

  echo "---- Plotting indices ----"
  $m2p dust_beta_c0001_k$num.fits  -bar -min 1.3 -max 2.0
  $m2p dust_Td_c0001_k$num.fits  -bar -min 14 -max 30
  #$m2p dust_Td_c0001_k$num_nosmooth.fits  -bar -min 14 -max 30
  $m2p synch_beta_c0001_k$num.fits  -bar -min -4.0 -max -1.5
  $m2p ame1_nup_c0001_k$num.fits  -bar -min 17 -max 23
  $m2p ame2_nup_c0001_k$num.fits  -bar -min 15 -max 40

  $m2p ff_EM_c0001_k$num.fits  -bar -min 0 -max 100
  $m2p ff_T_e_c0001_k$num.fits  -bar -min 5000 -max 8000
  $m2p ff_c0001_k$num.fits -bar -min 0 -max 1e6

  echo "---- Plotting residuals ----"
  freqs=("30" "44" "70" "100" "143" "217" "353" "545" "857" "WMAP" "Haslam")

  COUNTER=0
  for ((i=0; i<${#freqs[@]}; i++)) ; do
    freq=${freqs[$i]} #Frequency
    for file in res*${freq}*_c01_k$num.fits; do

      if [[ $file = *\** ]]; then #Check if contains wildcard (Map does not exist)
        echo "WARNING: " $file " does not exist!"
        continue
      fi

#      if [ $freq == 545 ] || [ $freq == 857 ] ; then
#        $m2p -bar -range 1e-2 $file
#	$m2p -bar -range 3e-2 $file ${file/.fits/_range3e-2.png}
      if [ $freq == 857 ] ; then
        $m2p -bar -range 3000 $file ${file/.fits/_range3k.png}
        $m2p -bar -range 30000 $file ${file/.fits/_range30k.png}
        $m2p -bar -range 10000 $file ${file/.fits/_range10k.png}
      elif [ $freq == 545 ] ; then
        $m2p -bar -range 100 $file ${file/.fits/_range100.png}
        $m2p -bar -range 300 $file ${file/.fits/_range300.png}
      elif [ "$freq" = "Haslam" ] ; then
        $m2p -bar -range 1e6 $file
      else
        $m2p -bar -range 10 $file
	if [ $freq == 353 ]; then
	    $m2p -bar -range 30 $file ${file/.fits/_range30.png}
	fi
      fi
      echo "Plotting" $file
      COUNTER=$[$COUNTER +1]
    done
  done

  mx=$((2 * $COUNTER))
  echo "---- Plotting chisq with max of" $mx "----"
  $m2p chisq_c0001_k$num.fits chisq_k$num.png -bar -max $mx -min 0 #max is 2*numband
  echo " "

  for file in *k$num.png *k${num}_range30.png *k${num}_range300.png *k${num}_*n0064.png *k${num}_range100.png *k${num}_range3k.png *k${num}_range10k.png *k${num}_range30k.png *k${num}_*ptsrc.png; do
      mv $file ${file/.png/_${version}.png}
  done

done

