#!/bin/bash


if [ $# -ne 1 ] && [ $# -ne 3 ] && [ $# -ne 3 ] && [ $# -ne 4 ]; then
  echo "plot_all_maps [sample number #####] ( [nside] [arcmins] [l_max for smoothing] )"
  echo "If optional options are given, only file with names containing these will be plotted."
  echo "If l_max is given, the original files will be smoothed to l_max with an [arcmins] "
  echo "beam and ud_graded to nside before it is plotted."
  exit
fi

num=$(printf "%06d\n" $1)    # sample number
nside=$(printf "%04d\n" $2)     # nside of output, if less than 2048 used ud_grade down after smoothing
arcmins=$3
lmax=$4




# To plot something reasonable we should smooth a little
me=~/quiet_svn/oslo/src/f90/map_editor/map_editor



if [ -n $lmax ]
then
    maps=(
	"res_030_c0001_k"${num}".fits"
	"res_044_c0001_k"${num}".fits"
	"res_070_c0001_k"${num}".fits"
	"cmb_c0001_k"${num}".fits"
	#"co10_100-1_c0001_k"${num}".fits"
	#"co10_100-2_c0001_k"${num}".fits"
	#"co10_100-3_c0001_k"${num}".fits"
	#"co10_100-4_c0001_k"${num}".fits"
	#"co10_100-1a_c0001_k"${num}".fits"
	#"co10_100-1b_c0001_k"${num}".fits"
	#"co10_100-2a_c0001_k"${num}".fits"
	#"co10_100-2b_c0001_k"${num}".fits"
	#"co10_100-3a_c0001_k"${num}".fits"
	#"co10_100-3b_c0001_k"${num}".fits"
	#"co10_100-4a_c0001_k"${num}".fits"
	#"co10_100-4b_c0001_k"${num}".fits"
	"co10_c0001_k"${num}".fits"
	#"co21_217-1_c0001_k"${num}".fits"
	#"co21_217-2_c0001_k"${num}".fits"
	#"co21_217-3_c0001_k"${num}".fits"
	#"co21_217-4_c0001_k"${num}".fits"
	#"co21_217-5a_c0001_k"${num}".fits"
	#"co21_217-5b_c0001_k"${num}".fits"
	#"co21_217-5_c0001_k"${num}".fits"
	#"co21_217-6a_c0001_k"${num}".fits"
	#"co21_217-6b_c0001_k"${num}".fits"
	#"co21_217-6_c0001_k"${num}".fits"
	#"co21_217-7a_c0001_k"${num}".fits"
	#"co21_217-7b_c0001_k"${num}".fits"
	#"co21_217-7_c0001_k"${num}".fits"
	#"co21_217-8a_c0001_k"${num}".fits"
	#"co21_217-8b_c0001_k"${num}".fits"
	#"co21_217-8_c0001_k"${num}".fits"
	"co21_c0001_k"${num}".fits"
	#"co32_353-3_c0001_k"${num}".fits"
	#"co32_353-4_c0001_k"${num}".fits"
	"co32_c0001_k"${num}".fits"
	"dust_beta_c0001_k"${num}".fits"
	"dust_T_c0001_k"${num}".fits"
	#"res_100-1_c0001_k"${num}".fits"
	#"res_100-2_c0001_k"${num}".fits"
	#"res_100-3_c0001_k"${num}".fits"
	#"res_100-4_c0001_k"${num}".fits"
	"res_100-1a_c0001_k"${num}".fits"
	"res_100-1b_c0001_k"${num}".fits"
	"res_100-2a_c0001_k"${num}".fits"
	"res_100-2b_c0001_k"${num}".fits"
	"res_100-3a_c0001_k"${num}".fits"
	"res_100-3b_c0001_k"${num}".fits"
	"res_100-4a_c0001_k"${num}".fits"
	"res_100-4b_c0001_k"${num}".fits"
	"res_143_c0001_k"${num}".fits"
	#"res_217-1_c0001_k"${num}".fits"
	"res_217-2_c0001_k"${num}".fits"
	"res_217-3_c0001_k"${num}".fits"
	#"res_217-4_c0001_k"${num}".fits"
	#"res_217-5_c0001_k"${num}".fits"
	"res_217-5a_c0001_k"${num}".fits"
	"res_217-5b_c0001_k"${num}".fits"
	"res_217-6_c0001_k"${num}".fits"
	#"res_217-6a_c0001_k"${num}".fits"
	#"res_217-6b_c0001_k"${num}".fits"
	#"res_217-7_c0001_k"${num}".fits"
	"res_217-7a_c0001_k"${num}".fits"
	"res_217-7b_c0001_k"${num}".fits"
	#"res_217-8a_c0001_k"${num}".fits"
	#"res_217-8b_c0001_k"${num}".fits"
	"res_217-8_c0001_k"${num}".fits"
	#"res_353-1_c0001_k"${num}".fits"
	#"res_353-2_c0001_k"${num}".fits"
	#"res_353-3a_c0001_k"${num}".fits"
	#"res_353-3b_c0001_k"${num}".fits"
	"res_353-3_c0001_k"${num}".fits"
	#"res_353-4a_c0001_k"${num}".fits"
	#"res_353-4b_c0001_k"${num}".fits"
	"res_353-4_c0001_k"${num}".fits"
	#"res_353-5a_c0001_k"${num}".fits"
	#"res_353-5b_c0001_k"${num}".fits"
	#"res_353-5_c0001_k"${num}".fits"
	#"res_353-6a_c0001_k"${num}".fits"
	#"res_353-6b_c0001_k"${num}".fits"
	#"res_353-6_c0001_k"${num}".fits"
	#"res_353-7_c0001_k"${num}".fits"
	#"res_353-8_c0001_k"${num}".fits"
	#"res_545-1_c0001_k"${num}".fits"
	"res_545-2_c0001_k"${num}".fits"
	#"res_545-4_c0001_k"${num}".fits"
	#"res_857-1_c0001_k"${num}".fits"
	"res_857-2_c0001_k"${num}".fits"
	#"res_857-3_c0001_k"${num}".fits"
	#"res_857-4_c0001_k"${num}".fits"
	"synch_beta_c0001_k"${num}".fits"
    )

    maps_more_l=(
	"synch_c0001_k"${num}".fits"
	"dust_c0001_k"${num}".fits"
	"chisq_c0001_k"${num}".fits"
    )

    echo "smoothing to "$arcmins" arcmin"
    for i in ${!maps[@]}; do
	if [ $i -lt 3 ]
	then
	    echo "LFI"
	    $me smooth g2g ${maps[$i]} 0 $lmax 1024 0. $arcmins ${maps[$i]/.fits/_highres_${arcmins}arcmin.fits}
	else
	     echo "HFI"
	    $me smooth g2g ${maps[$i]} 0 $lmax 2048 0. $arcmins ${maps[$i]/.fits/_highres_${arcmins}arcmin.fits}
	fi
	echo $(($i + 1)) of $((${#maps[@]}+${#maps_more_l[@]})) finished
    done

    for i in ${!maps_more_l[@]}; do
	$me smooth g2g ${maps_more_l[$i]} 0 $(($lmax + 200)) 2048 0. $arcmins ${maps_more_l[$i]/.fits/_highres_${arcmins}arcmin.fits}
	echo $(($i + 1 + ${#maps[@]})) of $((${#maps[@]}+${#maps_more_l[@]})) finished
    done

    

fi

echo "plotting maps"
if [ $nside = '2048' ] 
then
    echo "Plotting amplitudes"
    map2png dust_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -max 1000 -min 0.
    map2png synch_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -max 1000. -min 0.
    #map2png co10_100-1_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-2_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-3_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-4_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-1a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-1b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-2a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-2b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-3a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-3b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-4a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-4b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    map2png co10_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 10.
    #map2png co21_217-1_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-2_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-3_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-4_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-5a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-5b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-5_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-6a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-6b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-6_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-7a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-7b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-7_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-8a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-8b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-8_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    map2png co21_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 10.
    #map2png co32_353-3_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co32_353-4_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 2.
    map2png co32_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 10.


    map2png cmb_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 250
    map2png dust_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 1000. 

    echo "Plotting indices"
    map2png dust_beta_c0001_k${num}_highres_${arcmins}arcmin.fits  -bar -min 1.3 -max 2.0
    map2png dust_T_c0001_k${num}_highres_${arcmins}arcmin.fits  -bar -min 14. -max 30.
    map2png synch_beta_c0001_k${num}_highres_${arcmins}arcmin.fits  -bar -min -4.0 -max -1.5

    echo "Plotting chisq"
    map2png chisq_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -min 0. -max 60.


    echo "plotting residuals"
    map2png res_030_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_044_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_070_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_100-1_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_100-2_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_100-3_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_100-4_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-1a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-1b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-2a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-2b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-3a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-3b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-4a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-4b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_143_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-1_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-2_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-3_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-4_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-5_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-5a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-5b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-6_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-6a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-6b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-7_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-7a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-7b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-8a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-8b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-8_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-1_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-2_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-3a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-3b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_353-3_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-4a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-4b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_353-4_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-5a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-5b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-5_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-6a_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-6b_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-6_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-7_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-8_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_545-1_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_545-2_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 0.010
    #map2png res_545-4_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_857-1_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    map2png res_857-2_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 0.010
    #map2png res_857-3_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_857-4_c0001_k${num}_highres_${arcmins}arcmin.fits -bar -range 10.

else
    echo "ud_grading"
    for i in ${!maps[@]}; do
	$me ud_grade ${maps[$i]/.fits/_highres_${arcmins}arcmin.fits} $nside ${maps[$i]/.fits/_n${nside}_${arcmins}arcmin.fits}
	echo $(($i + 1)) of $((${#maps[@]}+${#maps_more_l[@]})) finished
    done

    for i in ${!maps_more_l[@]}; do
	$me ud_grade ${maps_more_l[$i]/.fits/_highres_${arcmins}arcmin.fits} $nside ${maps_more_l[$i]/.fits/_n${nside}_${arcmins}arcmin.fits}
	echo $(($i + 1 + ${#maps[@]})) of $((${#maps[@]}+${#maps_more_l[@]})) finished
    done


    echo "Plotting amplitudes"
    map2png dust_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -max 1000
    map2png synch_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -max 1000. -min 0.
    #map2png co10_100-1_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-2_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-3_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-4_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-1a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-1b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-2a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-2b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-3a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-3b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-4a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co10_100-4b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    map2png co10_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 10.
    #map2png co21_217-1_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-2_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-3_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-4_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-5a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-5b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-5_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-6a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-6b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-6_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-7a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-7b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-7_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-8a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-8b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co21_217-8_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    map2png co21_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 10.
    #map2png co32_353-3_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    #map2png co32_353-4_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 2.
    map2png co32_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 10.


    map2png cmb_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 250
    map2png dust_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 1000. 

    echo "Plotting indices"
    map2png dust_beta_c0001_k${num}_n${nside}_${arcmins}arcmin.fits  -bar -min 1.3 -max 2.0
    map2png dust_T_c0001_k${num}_n${nside}_${arcmins}arcmin.fits  -bar -min 14. -max 30.
    map2png synch_beta_c0001_k${num}_n${nside}_${arcmins}arcmin.fits  -bar -min -4.0 -max -1.5

    echo "Plotting chisq"
    map2png chisq_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -min 0. -max 80.


    echo "plotting residuals"
    map2png res_030_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_044_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_070_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_100-1_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_100-2_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_100-3_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_100-4_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-1a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-1b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-2a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-2b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-3a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-3b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-4a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_100-4b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_143_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-1_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-2_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-3_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-4_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-5_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-5a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-5b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-6_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-6a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-6b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-7_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-7a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-7b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-8a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_217-8b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_217-8_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-1_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-2_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-3a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-3b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_353-3_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-4a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-4b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_353-4_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-5a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-5b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-5_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-6a_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-6b_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-6_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-7_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_353-8_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_545-1_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_545-2_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 0.010
    #map2png res_545-4_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_857-1_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    map2png res_857-2_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 0.010
    #map2png res_857-3_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.
    #map2png res_857-4_c0001_k${num}_n${nside}_${arcmins}arcmin.fits -bar -range 10.

fi
