#!/bin/bash
export OMP_NUM_THREADS=24

#maped=~/quietsvn/oslo/src/f90/map_editor/map_editor
maped=/mn/stornext/u3/hke/local/bin/map_editor

map2png=/mn/stornext/u3/hke/local/bin/map2png

prefix="npipe4v207_v1"
rfill="10"

#outfreq=(030 044 070 100 143 217 353)
#infreq=(030 044 070 100 143 217 353)
#outfreq=(100 143 217 353)
#infreq=(100 143 217 353)
outfreq=(030 044 070)
infreq=(030 044 070)
#outfreq=(545_1 545_2 545_4 857_1 857_2 857_3 857_4)
#infreq=(545-1 545-2 545-4 857-1 857-2 857-3 857-4)

#bsize=(60 40 10 7.5)
#nside=(0256 0256 1024 2048)
#lmax=(1024 1024 4096 8192)
#bsize=(60)
#nside=(0016)
#lmax=(64)

bsize=(60 420 60 40)
nside=(0016 0032 0256 0256)
lmax=(48 96 768 768)

bsize=(40)
nside(0256)
lmax=(768)

#outset=(full yr1 yr2 hm1 hm2 hr1 hr2)
#inset=(full yr1 yr2 hm1 hm2 full_hr1 full_hr2)
outset=(full)
inset=(full)


for (( f=0; f<${#infreq[@]}; f++ )); do
    echo ${infreq[f]%%_*}
done

for (( b=0; b<${#bsize[@]}; b++ )); do
    for (( s=0; s<${#inset[@]}; s++ )); do
	for (( f=0; f<${#infreq[@]}; f++ )); do
	    echo ${bsize[$b]} ${nside[$b]} ${outset[$s]} ${outfreq[$f]}
	    $maped smooth f2g \
		npipe4v207/npipe4v207_${infreq[$f]}_map.fits \
		0 ${lmax[$b]} ${nside[$b]} \
		beam_dx12_${outfreq[$f]%%_*}x${outfreq[$f]%%_*}_extended_npipe4.fits ${bsize[$b]} \
		map_${prefix}_${outfreq[$f]}_${nside[$b]}_${bsize[$b]}arcmin_${outset[$s]}.fits \
		${rfill}
	    $maped scale \
		map_${prefix}_${outfreq[$f]}_${nside[$b]}_${bsize[$b]}arcmin_${outset[$s]}.fits \
		map_${prefix}_${outfreq[$f]}_${nside[$b]}_${bsize[$b]}arcmin_${outset[$s]}.fits 1e6
	    if [ "${outfreq[f]%%-*}" == "353" ]; then
		trange="-min 500 -max 1500"
		prange="-range 50"
	    else
 		trange="-range 500"
 		prange="-range 20"
	    fi
	    $map2png -bar $trange \
		map_${prefix}_${outfreq[$f]}_${nside[$b]}_${bsize[$b]}arcmin_${outset[$s]}.fits \
		map_${prefix}_${outfreq[$f]}_${nside[$b]}_${bsize[$b]}arcmin_${outset[$s]}_T.png
	    $map2png -bar -sig 2 -sig 3 -size 600 $prange \
		map_${prefix}_${outfreq[$f]}_${nside[$b]}_${bsize[$b]}arcmin_${outset[$s]}.fits \
		map_${prefix}_${outfreq[$f]}_${nside[$b]}_${bsize[$b]}arcmin_${outset[$s]}_P.png
	done
    done
done
